"""Regenerate the registry-derived wiki pages.

Usage (from anywhere inside the repository):
    python .claude/skills/model-release/scripts/regen_wiki.py          # rewrite pages
    python .claude/skills/model-release/scripts/regen_wiki.py --check  # report drift only

Rewrites, from `gaise-core/model-registry.toml`:
- the `## Models` table of every `wiki/vendor-<provider>.md` page, one row per
  `registry_json` entry in registry order;
- the generated regions of `wiki/limits.md`, `wiki/reasoning.md`, and
  `wiki/embeddings.md` (from the `<!-- Generated by` marker to the next `## `);
- `wiki/models.md` in full.

The TypeSafe sections of `wiki/limits.md` and `wiki/models.md` are
hand-written, so they are copied from the current file into the regenerated
text. Every file is written back with CRLF line endings, matching the working
tree under `core.autocrlf`.
"""
import io
import json
import subprocess
import sys

ROOT = subprocess.run(
    ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True
).stdout.strip() + "/"
CHECK = "--check" in sys.argv
VENDORS = ["openai", "anthropic", "gemini", "vertexai", "bedrock", "ollama", "elevenlabs"]
TABLE_HEAD = (
    "| Model | Aliases | Status | Dates | Input | Output | Operations | Reasoning values | GAISe support | Notes |\n"
    "|---|---|---|---|---|---|---|---|---|---|\n"
)
drift = []


def read(path):
    with io.open(ROOT + path, newline="", encoding="utf-8") as f:
        return f.read().replace("\r\n", "\n")


def write(path, text):
    if read(path) == text:
        return
    drift.append(path)
    if not CHECK:
        with io.open(ROOT + path, "w", newline="", encoding="utf-8") as f:
            f.write(text.replace("\n", "\r\n"))


def cargo(*args):
    out = subprocess.run(["cargo", "run", "-q", *args], cwd=ROOT, capture_output=True, check=True)
    return out.stdout.decode("utf-8").replace("\r\n", "\n")


def cut(text, limit=140):
    return text if len(text) <= limit else text[:limit].rstrip() + "…"


def row(m):
    c = m["classified"]
    ticks = lambda xs: ", ".join(f"`{x}`" for x in xs) if xs else "—"
    dates = []
    if m.get("shutdown_date"):
        dates.append(f"shutdown {m['shutdown_date']}")
    if m.get("retirement_not_before"):
        dates.append(f"not before {m['retirement_not_before']}")
    notes = cut(m["notes"]) if m.get("notes") else ""
    if m.get("replacement") and not notes.endswith("…"):
        notes = (notes + " " if notes else "") + f"Replacement `{m['replacement']}`."
    if m.get("reasoning_values"):
        reasoning = ticks(m["reasoning_values"])
    elif c["reasoning"] == "supported":
        if "manual_reasoning" in c["features"]:
            reasoning = "manual budget"
        elif "adaptive_reasoning" in c["features"]:
            reasoning = "adaptive"
        else:
            reasoning = "supported"
    else:
        reasoning = "—"
    cells = [
        f"`{m['model']}`",
        ticks(m["aliases"]),
        f"`{m['status']}`",
        ", ".join(dates) or "—",
        ", ".join(c["input"]) or "unknown",
        ", ".join(c["output"]) or "unknown",
        ", ".join(c["operations"]) or "—",
        reasoning,
        m.get("gaise_support") or "—",
        notes or "—",
    ]
    return "| " + " | ".join(cells) + " |"


def section(text, start, end):
    i = text.index(start)
    return i, text.index(end, i)


registry = json.loads(cargo("-p", "gaise", "--example", "registry_json"))

for provider in VENDORS:
    path = f"wiki/vendor-{provider}.md"
    text = read(path)
    rows = "\n".join(row(m) for m in registry["models"] if m["provider"] == provider)
    start = text.index(TABLE_HEAD, text.index("\n## Models\n")) + len(TABLE_HEAD)
    end = text.index("\n\n", start)
    # "(audited YYYY-MM-DD)" headings are left alone: bump them by hand for
    # the providers that were actually re-audited.
    write(path, text[:start] + rows + text[end:])


def regenerate_region(path, generated, keep=None):
    """Replace the generated region; `keep` = (start, end) of a hand-written part."""
    text = read(path)
    marker = "<!-- Generated by"
    g_start = generated.index(marker)
    g_end = generated.find("\n## ", g_start)
    block = (generated[g_start:] if g_end < 0 else generated[g_start:g_end]).rstrip("\n") + "\n"
    start = text.index(marker)
    end = text.index("\n## ", start)
    if keep:
        k_start, k_end = section(text, *keep)
        b_start, b_end = section(block + keep[1], *keep)
        block = block[:b_start] + text[k_start:k_end] + block[b_end:]
    write(path, text[:start] + block + text[end:])


regenerate_region(
    "wiki/limits.md",
    cargo("-p", "gaise", "--example", "limits_matrix"),
    keep=("\n### TypeSafe AI\n", "\n## "),
)
regenerate_region(
    "wiki/reasoning.md",
    cargo("-p", "gaise-client", "--example", "reasoning_matrix", "--all-features"),
)
regenerate_region(
    "wiki/embeddings.md",
    cargo("-p", "gaise-client", "--example", "embedding_matrix", "--all-features"),
)

models = cargo("-p", "gaise", "--example", "models_page")
current = read("wiki/models.md")
keep = ("\n### TypeSafe AI\n", "\n## Lifecycle calendar\n")
n_start, n_end = section(models, *keep)
o_start, o_end = section(current, *keep)
models = models[:n_start] + current[o_start:o_end] + models[n_end:]
models = models.replace("- [TypeSafe AI](#typesafe) — 1 entries\n", "")
write("wiki/models.md", models)

if CHECK:
    print("drift:", ", ".join(drift) if drift else "none")
    sys.exit(1 if drift else 0)
print("updated:", ", ".join(drift) if drift else "nothing")
